# Generated by Django 3.1.5 on 2021-01-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210109_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugee',
            name='nationality',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
