# Generated by Django 3.1.5 on 2021-01-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210109_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='refugee',
            name='nationality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.nationality'),
        ),
    ]
