# Generated by Django 3.1.5 on 2021-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='message',
            field=models.CharField(default='', max_length=400),
        ),
    ]
