# Generated by Django 3.1.5 on 2021-01-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_refugee_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service2', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='refugee',
            name='message',
            field=models.CharField(default='', max_length=480),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.service'),
        ),
        migrations.AddField(
            model_name='refugee',
            name='service2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.service2'),
        ),
    ]
