# Generated by Django 3.1.5 on 2021-01-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210110_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='service2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.service2'),
        ),
    ]
