# Generated by Django 3.1.5 on 2021-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_refugee_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='case_status',
            field=models.BooleanField(default=True),
        ),
    ]
