# Generated by Django 3.1.5 on 2021-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210111_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='case_status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
