# Generated by Django 3.1.5 on 2021-01-11 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210111_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
