# Generated by Django 3.1.5 on 2021-01-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_refugee_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='phone_number',
            field=models.IntegerField(max_length=11),
        ),
    ]
