# Generated by Django 3.1.5 on 2021-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210112_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
